name: Build Electron App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build application
      run: npm run build
      continue-on-error: true
      
    - name: Run tests
      run: npm test
      continue-on-error: true
      
    - name: Package Electron app
      run: npm run dist
      continue-on-error: true
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: electron-app-${{ matrix.os }}-${{ matrix.node-version }}
        path: |
          badr-desktop/dist/
          badr-desktop/build/
          dist/
          build/
          badr-desktop/*.exe
          badr-desktop/*.dmg
          badr-desktop/*.AppImage
          badr-desktop/*.deb
          badr-desktop/*.rpm
        retention-days: 30
        if-no-files-found: ignore
        
  # وظيفة إضافية لإنشاء Release عند وجود tag
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build and package
      run: |
        npm run build
        npm run dist
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.exe
          dist/*.dmg
          dist/*.AppImage
          dist/*.deb
          dist/*.rpm
          badr-desktop/dist/*.exe
          badr-desktop/dist/*.dmg
          badr-desktop/dist/*.AppImage
          badr-desktop/dist/*.deb
          badr-desktop/dist/*.rpm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

